In [ ]:
from google.colab import files
uploaded = files.upload()

Saving country.csv to country (1).csv

In [ ]:
import pandas as pd
df = pd.read_csv("country.csv")
df.head()

,Country,Region,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Coastline (coast/area ratio),Net migration,Infant mortality (per 1000 births),GDP ($ per capita),Literacy (%),Phones (per 1000),Arable (%),Crops (%),Other (%),Climate,Birthrate,Deathrate,Agriculture,Industry,Service
0,Afghanistan,ASIA (EX. NEAR EAST),31056997,647500,"48,0","0,00","23,06","163,07",700.0,"36,0","3,2","12,13","0,22","87,65",1,"46,6","20,34","0,38","0,24","0,38"
1,Albania,EASTERN EUROPE,3581655,28748,"124,6","1,26","-4,93","21,52",4500.0,"86,5","71,2","21,09","4,42","74,49",3,"15,11","5,22","0,232","0,188","0,579"
2,Algeria,NORTHERN AFRICA,32930091,2381740,"13,8","0,04","-0,39",31,6000.0,"70,0","78,1","3,22","0,25","96,53",1,"17,14","4,61","0,101","0,6","0,298"
3,American Samoa,OCEANIA,57794,199,"290,4","58,29","-20,71","9,27",8000.0,"97,0","259,5",10,15,75,2,"22,46","3,27",NaN,NaN,NaN
4,Andorra,WESTERN EUROPE,71201,468,"152,1","0,00","6,6","4,05",19000.0,"100,0","497,2","2,22",0,"97,78",3,"8,71","6,25",NaN,NaN,NaN

In [ ]:
df_sorted = df.sort_values(by="Population", ascending=False)
df_sorted.head(20)

,Country,Region,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Coastline (coast/area ratio),Net migration,Infant mortality (per 1000 births),GDP ($ per capita),Literacy (%),Phones (per 1000),Arable (%),Crops (%),Other (%),Climate,Birthrate,Deathrate,Agriculture,Industry,Service
42,China,ASIA (EX. NEAR EAST),1313973713,9596960,"136,9","0,15","-0,4","24,18",5000.0,"90,9","266,7","15,4","1,25","83,35","1,5","13,25","6,97","0,125","0,473","0,403"
94,India,ASIA (EX. NEAR EAST),1095351995,3287590,"333,2","0,21","-0,07","56,29",2900.0,"59,5","45,4","54,4","2,74","42,86","2,5","22,01","8,18","0,186","0,276","0,538"
214,United States,NORTHERN AMERICA,298444215,9631420,"31,0","0,21","3,41","6,5",37800.0,"97,0","898,0","19,13","0,22","80,65",3,"14,14","8,26","0,01","0,204","0,787"
95,Indonesia,ASIA (EX. NEAR EAST),245452739,1919440,"127,9","2,85",0,"35,6",3200.0,"87,9","52,0","11,32","7,23","81,45",2,"20,34","6,25","0,134","0,458","0,408"
27,Brazil,LATIN AMER. & CARIB,188078227,8511965,"22,1","0,09","-0,03","29,61",7600.0,"86,4","225,3","6,96","0,9","92,15",2,"16,56","6,17","0,084","0,4","0,516"
156,Pakistan,ASIA (EX. NEAR EAST),165803560,803940,"206,2","0,13","-2,77","72,44",2100.0,"45,7","31,8","27,87","0,87","71,26",1,"29,74","8,23","0,216","0,251","0,533"
16,Bangladesh,ASIA (EX. NEAR EAST),147365352,144000,"1023,4","0,40","-0,71","62,6",1900.0,"43,1","7,3","62,11","3,07","34,82",2,"29,8","8,27","0,199","0,198","0,603"
169,Russia,C.W. OF IND. STATES,142893540,17075200,"8,4","0,22","1,02","15,39",8900.0,"99,6","280,6","7,33","0,11","92,56",NaN,"9,95","14,65","0,054","0,371","0,575"
152,Nigeria,SUB-SAHARAN AFRICA,131859731,923768,"142,7","0,09","0,26","98,8",900.0,"68,0","9,3","31,29","2,96","65,75","1,5","40,43","16,94","0,269","0,487","0,244"
103,Japan,ASIA (EX. NEAR EAST),127463611,377835,"337,4","7,87",0,"3,26",28200.0,"99,0","461,2","12,19","0,96","86,85",3,"9,37","9,16","0,017","0,258","0,725"
135,Mexico,LATIN AMER. & CARIB,107449525,1972550,"54,5","0,47","-4,87","20,91",9000.0,"92,2","181,6","12,99","1,31","85,7","1,5","20,69","4,74","0,038","0,259","0,702"
162,Philippines,ASIA (EX. NEAR EAST),89468677,300000,"298,2","12,10","-1,5","23,51",4600.0,"92,6","38,4","18,95","16,77","64,28",2,"24,89","5,41","0,144","0,326","0,53"
219,Vietnam,ASIA (EX. NEAR EAST),84402966,329560,"256,1","1,05","-0,45","25,95",2500.0,"90,3","187,7","19,97","5,95","74,08",2,"16,86","6,22","0,209","0,41","0,381"
76,Germany,WESTERN EUROPE,82422299,357021,"230,9","0,67","2,18","4,16",27600.0,"99,0","667,9","33,85","0,59","65,56",3,"8,25","10,62","0,009","0,296","0,695"
60,Egypt,NORTHERN AFRICA,78887007,1001450,"78,8","0,24","-0,22","32,59",4000.0,"57,7","131,8","2,87","0,48","96,65",1,"22,94","5,23","0,149","0,357","0,493"
65,Ethiopia,SUB-SAHARAN AFRICA,74777981,1127127,"66,3","0,00",0,"95,32",700.0,"42,7","8,2","10,71","0,75","88,54",2,"37,98","14,86","0,475","0,099","0,426"
206,Turkey,NEAR EAST,70413958,780580,"90,2","0,92",0,"41,04",6700.0,"86,5","269,5","30,93","3,31","65,76",3,"16,62","5,97","0,117","0,298","0,585"
96,Iran,ASIA (EX. NEAR EAST),68688433,1648000,"41,7","0,15","-0,84","41,58",7000.0,"79,4","276,4","8,72","1,39","89,89",1,17,"5,55","0,116","0,424","0,46"
201,Thailand,ASIA (EX. NEAR EAST),64631595,514000,"125,7","0,63",0,"20,48",7400.0,"92,6","108,9","29,36","6,46","64,18",2,"13,87","7,04","0,099","0,441","0,46"
45,"Congo, Dem. Rep.",SUB-SAHARAN AFRICA,62660551,2345410,"26,7","0,00",0,"94,69",700.0,"65,5","0,2","2,96","0,52","96,52",2,"43,69","13,27","0,55","0,11","0,34"

In [ ]:
df_gdp_sorted = df.sort_values(by="GDP ($ per capita)", ascending=True)
df_gdp_sorted.head(10)

,Country,Region,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Coastline (coast/area ratio),Net migration,Infant mortality (per 1000 births),GDP ($ per capita),Literacy (%),Phones (per 1000),Arable (%),Crops (%),Other (%),Climate,Birthrate,Deathrate,Agriculture,Industry,Service
58,East Timor,ASIA (EX. NEAR EAST),1062777,15007,"70,8","4,70",0,"47,41",500.0,"58,6",NaN,"4,71","0,67","94,62",2,"26,99","6,24","0,085","0,231","0,684"
183,Sierra Leone,SUB-SAHARAN AFRICA,6005250,71740,"83,7","0,56",0,"143,64",500.0,"31,4","4,0","6,98","0,89","92,13",2,"45,76","23,03","0,49","0,31","0,21"
188,Somalia,SUB-SAHARAN AFRICA,8863338,637657,"13,9","0,47","5,37","116,7",500.0,"37,8","11,3","1,67","0,04","98,29",1,"45,13","16,63","0,65","0,1","0,25"
33,Burundi,SUB-SAHARAN AFRICA,8090068,27830,"290,7","0,00","-0,06","69,29",600.0,"51,6","3,4","35,05","14,02","50,93",2,"42,22","13,46","0,463","0,203","0,334"
125,Malawi,SUB-SAHARAN AFRICA,13013926,118480,"109,8","0,00",0,"103,32",600.0,"62,7","7,9","23,38","1,49","75,13",2,"43,13","19,33","0,342","0,158","0,499"
200,Tanzania,SUB-SAHARAN AFRICA,37445392,945087,"39,6","0,15","-2,06","98,54",600.0,"78,2","4,0","4,52","1,08","94,4",NaN,"37,71","16,39","0,432","0,172","0,396"
74,Gaza Strip,NEAR EAST,1428757,360,"3968,8","11,11","1,6","22,93",600.0,NaN,"244,3","28,95","21,05",50,3,"39,45","3,8","0,03","0,283","0,687"
44,Comoros,SUB-SAHARAN AFRICA,690948,2170,"318,4","15,67",0,"74,93",700.0,"56,5","24,5","35,87","23,32","40,81",2,"36,93","8,2","0,4","0,04","0,56"
45,"Congo, Dem. Rep.",SUB-SAHARAN AFRICA,62660551,2345410,"26,7","0,00",0,"94,69",700.0,"65,5","0,2","2,96","0,52","96,52",2,"43,69","13,27","0,55","0,11","0,34"
65,Ethiopia,SUB-SAHARAN AFRICA,74777981,1127127,"66,3","0,00",0,"95,32",700.0,"42,7","8,2","10,71","0,75","88,54",2,"37,98","14,86","0,475","0,099","0,426"

In [ ]:
df_pop_over_10m = df[df["Population"] > 10000000]
df_pop_over_10m.head()

,Country,Region,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Coastline (coast/area ratio),Net migration,Infant mortality (per 1000 births),GDP ($ per capita),Literacy (%),Phones (per 1000),Arable (%),Crops (%),Other (%),Climate,Birthrate,Deathrate,Agriculture,Industry,Service
0,Afghanistan,ASIA (EX. NEAR EAST),31056997,647500,"48,0","0,00","23,06","163,07",700.0,"36,0","3,2","12,13","0,22","87,65",1,"46,6","20,34","0,38","0,24","0,38"
2,Algeria,NORTHERN AFRICA,32930091,2381740,"13,8","0,04","-0,39",31,6000.0,"70,0","78,1","3,22","0,25","96,53",1,"17,14","4,61","0,101","0,6","0,298"
5,Angola,SUB-SAHARAN AFRICA,12127071,1246700,"9,7","0,13",0,"191,19",1900.0,"42,0","7,8","2,41","0,24","97,35",NaN,"45,11","24,2","0,096","0,658","0,246"
8,Argentina,LATIN AMER. & CARIB,39921833,2766890,"14,4","0,18","0,61","15,18",11200.0,"97,1","220,4","12,31","0,48","87,21",3,"16,73","7,55","0,095","0,358","0,547"
11,Australia,OCEANIA,20264082,7686850,"2,6","0,34","3,98","4,69",29000.0,"100,0","565,5","6,55","0,04","93,41",1,"12,14","7,51","0,038","0,262","0,7"

In [ ]:
df_literacy_sorted = df.sort_values(by="Literacy (%)", ascending=False)
df_literacy_sorted.head(5)

,Country,Region,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Coastline (coast/area ratio),Net migration,Infant mortality (per 1000 births),GDP ($ per capita),Literacy (%),Phones (per 1000),Arable (%),Crops (%),Other (%),Climate,Birthrate,Deathrate,Agriculture,Industry,Service
53,Czech Republic,EASTERN EUROPE,10235455,78866,"129,8","0,00","0,97","3,93",15700.0,"99,9","314,3","39,8","3,05","57,15",3,"9,02","10,59","0,034","0,393","0,573"
93,Iceland,WESTERN EUROPE,299388,103000,"2,9","4,83","2,38","3,31",30900.0,"99,9","647,7","0,07",0,"99,93",3,"13,64","6,72","0,086","0,15","0,765"
163,Poland,EASTERN EUROPE,38536869,312685,"123,3","0,16","-0,49","8,51",11100.0,"99,8","306,3","45,91","1,12","52,97",3,"9,85","9,89","0,05","0,311","0,64"
114,Latvia,BALTICS,2274735,64589,"35,2","0,82","-2,23","9,55",10200.0,"99,8","321,4","29,67","0,47","69,86",3,"9,24","13,66","0,04","0,261","0,699"
64,Estonia,BALTICS,1324333,45226,"29,3","8,39","-3,16","7,87",12300.0,"99,8","333,8","16,04","0,45","83,51",3,"10,04","13,25","0,04","0,294","0,666"

In [ ]:
df_gdp_over_10k = df[df["GDP ($ per capita)"] > 10000]
df_gdp_over_10k.head()

,Country,Region,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Coastline (coast/area ratio),Net migration,Infant mortality (per 1000 births),GDP ($ per capita),Literacy (%),Phones (per 1000),Arable (%),Crops (%),Other (%),Climate,Birthrate,Deathrate,Agriculture,Industry,Service
4,Andorra,WESTERN EUROPE,71201,468,"152,1","0,00","6,6","4,05",19000.0,"100,0","497,2","2,22",0,"97,78",3,"8,71","6,25",NaN,NaN,NaN
7,Antigua & Barbuda,LATIN AMER. & CARIB,69108,443,"156,0","34,54","-6,15","19,46",11000.0,"89,0","549,9","18,18","4,55","77,27",2,"16,93","5,37","0,038","0,22","0,743"
8,Argentina,LATIN AMER. & CARIB,39921833,2766890,"14,4","0,18","0,61","15,18",11200.0,"97,1","220,4","12,31","0,48","87,21",3,"16,73","7,55","0,095","0,358","0,547"
10,Aruba,LATIN AMER. & CARIB,71891,193,"372,5","35,49",0,"5,89",28000.0,"97,0","516,1","10,53",0,"89,47",2,"11,03","6,68","0,004","0,333","0,663"
11,Australia,OCEANIA,20264082,7686850,"2,6","0,34","3,98","4,69",29000.0,"100,0","565,5","6,55","0,04","93,41",1,"12,14","7,51","0,038","0,262","0,7"

In [ ]:
df_density_sorted = df.sort_values(by="Pop. Density (per sq. mi.)", ascending=False)
df_density_sorted.head(10)

,Country,Region,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Coastline (coast/area ratio),Net migration,Infant mortality (per 1000 births),GDP ($ per capita),Literacy (%),Phones (per 1000),Arable (%),Crops (%),Other (%),Climate,Birthrate,Deathrate,Agriculture,Industry,Service
9,Armenia,C.W. OF IND. STATES,2976372,29800,"99,9","0,00","-6,47","23,28",3500.0,"98,6","195,7","17,55","2,3","80,15",4,"12,07","8,23","0,239","0,343","0,418"
186,Slovenia,EASTERN EUROPE,2010347,20273,"99,2","0,23","1,12","4,45",19000.0,"99,7","406,1","8,6","1,49","89,91",NaN,"8,98","10,31","0,028","0,369","0,603"
202,Togo,SUB-SAHARAN AFRICA,5548702,56785,"97,7","0,10",0,"66,61",1500.0,"60,9","10,6","46,15","2,21","51,64",2,"37,01","9,83","0,395","0,204","0,401"
12,Austria,WESTERN EUROPE,8192880,83870,"97,7","0,00",2,"4,66",30000.0,"98,0","452,2","16,91","0,86","82,23",3,"8,74","9,76","0,018","0,304","0,678"
168,Romania,EASTERN EUROPE,22303552,237500,"93,9","0,09","-0,13","26,43",7000.0,"98,4","196,9","40,82","2,25","56,93",3,"10,7","11,77","0,101","0,35","0,549"
77,Ghana,SUB-SAHARAN AFRICA,22409572,239460,"93,6","0,23","-0,64","51,43",2200.0,"74,8","14,4","16,26","9,67","74,07",2,"30,52","9,72","0,366","0,246","0,387"
140,Montserrat,LATIN AMER. & CARIB,9439,102,"92,5","39,22",0,"7,35",3400.0,"97,0",NaN,20,0,80,2,"17,59","7,1",NaN,NaN,NaN
13,Azerbaijan,C.W. OF IND. STATES,7961619,86600,"91,9","0,00","-4,9","81,74",3400.0,"97,0","137,1","19,63","2,71","77,66",1,"20,74","9,75","0,141","0,457","0,402"
56,Dominica,LATIN AMER. & CARIB,68910,754,"91,4","19,63","-13,87","14,15",5400.0,"94,0","304,8","6,67",20,"73,33",2,"15,27","6,73","0,177","0,328","0,495"
206,Turkey,NEAR EAST,70413958,780580,"90,2","0,92",0,"41,04",6700.0,"86,5","269,5","30,93","3,31","65,76",3,"16,62","5,97","0,117","0,298","0,585"